version: '3.8'
services:
  auth-service:
    image: auth-service
    build:
      context: .
      dockerfile: apps/auth/Dockerfile # Path to Dockerfile for api-service
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=myDB
      - DB_USER=gourav
      - DB_PASSWORD=12345678
      - JWT_SECRET=mySecrete
      - JWT_EXPIRATION=3600
      - HTTP_PORT=3000
      - TCP_PORT=3001
    depends_on:
      - db
  product-service:
    image: product-service
    build:
      context: .
      dockerfile: apps/product/Dockerfile # Path to Dockerfile for api-service
    ports:
      - "3003:3003"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=myDB
      - DB_USER=gourav
      - DB_PASSWORD=12345678
      - HTTP_PORT=3003
      - TCP_PORT=3001
      - AUTH_HOST=auth-service
      - AUTH_PORT=3001
    depends_on:
      - db
      - auth-service
    
  cart-service:
    image: cart-service
    build:
      context: .
      dockerfile: apps/cart/Dockerfile # Path to Dockerfile for api-service
    ports:
      - "3004:3004"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=myDB
      - DB_USER=gourav
      - DB_PASSWORD=12345678
      - HTTP_PORT=3004
      - TCP_PORT=3001
      - AUTH_HOST=auth-service
      - AUTH_PORT=3001
    depends_on:
      - db
      - auth-service
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: gourav@123
      MYSQL_DATABASE: myDB
      MYSQL_USER: gourav
      MYSQL_PASSWORD: 12345678
    ports:
      - "3307:3306"
